### ISSUE TITLE
Background with image

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/patterns-plugin#13]
I will try this plugin out very soon, like next week.

However, I already have a suggestion. The `background` variable is nice.

I have some modules that needs a background image to see if they work well that are not a part of the module.

**Why it can be good with a background image:**
- You can see if a text is readable
- You can see if a text color still works visually

Maybe call it `background_url`

**Comment by therephil** [comment]
This also applies to elements that have to be wrapped in something to work or be visible.

Maybe use a wrap option (good stuff from the old version) where you can apply a wrapping structure for the single element preview. 

Would it be possible to use emmet for more complex wrapper?

```
'wrap' => '.someclass>.elementwrapper'
```

this way you could apply your background image to a wrapper. But it could also be an element that clears floats or whatever you need in your specific project to preview the element by itself.

**Comment by jenstornell** [comment]
I like the idea of a `wrap` variable but I don't like the emmet thing and I don't like html inside arrays. I hope we could use a snippet for it instead, quite much reminds me of this issue:

https://github.com/getkirby/panel/issues/747

**Comment by jenstornell** [comment]
I moved pattern wrap to a new issue. Then we can keep this issue about `background_url`.

https://github.com/getkirby/patterns/issues/22

**Comment by jenstornell** [comment]
And here comes a real case.

From the site where the background is an image and the menu has `background: rgba(0,0,0,.5);` (transparency)

![image](https://cloud.githubusercontent.com/assets/927011/12885099/6d94d55a-ce63-11e5-82b0-0705c43ca9bb.png)

How it looks in the Patterns plugin. It does not have a wood background so it looks gray.

![image](https://cloud.githubusercontent.com/assets/927011/12885112/88a6565c-ce63-11e5-9ba0-1a14a208f0d2.png)
