### ISSUE TITLE
Edit code directly in the browser

### ISSUE THREAD

**Issue by texnixe** [getkirby-v2/patterns-plugin#14]
Since it looks similar to my editor, I'm tempted to trying to edit directly in the browser, only to find that I have to return to my editor. That would be a killer feature ...;-) It's allowed to dream a bit, isn't it?

Great plugin, btw.

**Comment by jenstornell** [comment]
It would be really cool indeed. If it's going to work well it needs to be built on a really good editor. The downside of a good editor is that it's often heavy to load and we don't want to wait very long.

The best editor I've found it is https://ace.c9.io/ but it's a little bit slow on initial load. Maybe that's not a problem when it's cached in the browser.

**Comment by jenstornell** [comment]
I have thought about this again.

If we add some kind of editor, what will happend?

1. We will use the Patterns editor
1. That means we leave our favorite editor behind.
1. Then we become dependent on the editor in Patterns.
1. Then we will be frustrated by the lack of some features of a "real" editor, like auto completion.
1. Then we need file system features like, rename, move, copy, add, delete files and folders.

I think this feature alone can be 10 times bigger than Patterns is now and still would not be as good as a "real" editor.

Therefor I think it's better that they are separated.

I don't know if it would be possible to click on a file in Patterns to get it up in the "real" editor. The same with folders. That would be really cool. Kind of a workaround for this issue.

**Comment by shoesforindustry** [comment]
I usually have the whole site open in and editor, so having an editor in Patterns is not really necessary, but it would be cool to have links in Patterns to open files in your favourite editor ;-)

**Comment by texnixe** [comment]
> Then we need file system features like, rename, move, copy, add, delete files and folders.

Haha, true, I know someone who's very feature hungry :tongue: 

The workaround with linking to the file sounds like a good idea.

**Comment by jenstornell** [comment]
@texnixe You think? :wink:

It seems like the link idea was a little too good to be true:

http://stackoverflow.com/questions/18246053/how-can-i-create-a-link-to-a-local-file-on-a-locally-run-web-page

> These will never open the file in your local applications automatically. That's for security reasons, and I'll get to that in the last section. If it opens, it will only ever open in the browser. If it your browser can display the file, it will. If it can't, it will probably ask you if you want to download it.
