### ISSUE TITLE
Pattern wrap

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/patterns-plugin#22]
**From this issue:**

https://github.com/getkirby/patterns/issues/13

@therephil

> This also applies to elements that have to be wrapped in something to work or be visible.
> 
> Maybe use a wrap option (good stuff from the old version) where you can apply a wrapping structure for the single element preview.
> 
> Would it be possible to use emmet for more complex wrapper?
> 
> 'wrap' => '.someclass>.elementwrapper'
> this way you could apply your background image to a wrapper. But it could also be an element that clears floats or whatever you need in your specific project to preview the element by itself.

**My reply**

> I like the idea of a wrap variable but I don't like the emmet thing and I don't like html inside arrays. I hope we could use a snippet for it instead, quite much reminds me of this issue:
> 
> getkirby/panel#747

Today I noticed that this is a good idea. I need a padding around the pattern because the background of the Pattern plugin and the border left has the same color. It means I can't see if there is a border or not.

**Comment by jenstornell** [comment]
And now a real live example of why it would be awesome to add some kind of wrap that only are avialable in the Patterns plugin.

**Logo pattern**

It's fine!

![image](https://cloud.githubusercontent.com/assets/927011/12913257/ef7b11c8-cf1d-11e5-8e8b-0d32e2986e40.png)

**Hero pattern**

Not so fine. The logo pattern wraps the hero with a negative margin. It shows it correctly but this time I would like to push the hero 20-40px to the right.

![image](https://cloud.githubusercontent.com/assets/927011/12913279/06217a7a-cf1e-11e5-8ae3-297e65f6fba5.png)

**Comment by dweidner** [comment]
#36 could help here as well, as you can choose the markup used by the preview.
