### ISSUE TITLE
Multilanguage variables don't work

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/patterns-plugin#23]
https://getkirby.com/docs/languages/variables

The `l::get('somevar');` don't work inside a pattern. They work on frontend.

**Comment by jenstornell** [comment]
It's possible to to this as a workaround:

```php
<?php pattern('hero', ['label' => l::get('imagegallery')] ); ?>
```

But it gets quite messy when using it in nested patterns. Then it needs to be sent through all the patterns on the way there.

**Comment by lukaskleinschmidt** [comment]
For anyone with the same problem. I solved it with a custom route.

```php
// site/plugins/patterns-multilang.php

$kirby->set('route', [
  'pattern' => 'patterns/(:all?)',
  'action'  => function($path = null) {
    kirby()->localize();
    return Kirby\Patterns\Lab::instance()->run($path);
  }
]);
```
