### ISSUE TITLE
Override the page object does not work

### ISSUE THREAD

**Issue by jenstornell** [getkirby-v2/patterns-plugin#26]
Overriding the `page` object does not work.

``` php
<?php
return [
    'defaults' => [
        'page' => page('faq'),
    ]
];
```

**In the pattern this prints the home title instead:**

``` php
<?php echo $page->title(); ?>
```

**If I use another key it works:**

``` php
<?php
return [
    'defaults' => [
        'p' => page('faq'),
    ]
];
```

But because it should also work on the frontend it would be better if it used the same object.

**Comment by dweidner** [comment]
+1

**Comment by distantnative** [comment]
+1
