### ISSUE TITLE
Default styles not loading with `php -S ...`

### ISSUE THREAD

**Issue by maxxst** [getkirby-v2/patterns-plugin#31]
I made a fresh installation of kirby with plainkit. Then I followed the instructions to install the `patterns`-Plugin.

But when I then start a dev server with `php -S localhost:8000` I get this error message:

``` sh
127.0.0.1:61018 [404]: /assets/index.min.css - No such file or directory
```

If I do the same with MAMP on my Mac it works fine ...

**Comment by jenstornell** [comment]
Maybe it has problems with dots? The panel had that issue before it was rewritten. Can you somehow try it without dots in the filename?

**Comment by maxxst** [comment]
@jenstornell in what filename ?

**Comment by jenstornell** [comment]
This file:

`/assets/index.min.css`

Or check that this option matches your site:

```php
c::set('patterns.preview.css', 'assets/css/index.css');
```

**Comment by shoesforindustry** [comment]
Having the same problem, but OSX & nginx.
If I set
`c::set('patterns.preview.css', 'assets/index.css');`
I still get:
`<link rel="stylesheet" href="http://aap.dev/patterns/assets/index.min.css">`

Both files are there in `assets`, but I get an error in the nginx log...
`...[error] 243#0: *1227 open() "/Users/username/Sites/aap/aapcms/patterns/assets/index.min.css" failed (2: No such file or directory), client: 127.0.0.1, server: aap.dev, request: "GET /patterns/assets/index.min.css HTTP/1.1", host: "aap.dev", referrer: "http://aap.dev/patterns"`
Any ideas?

**Comment by jongacnik** [comment]
I am running into this issue as well. It might have to do with how the simple server handles routing. 

I went ahead and manually placed the css/js into `assets` which at least got the defaults styles/scripts going, but attempting to navigate to an actual pattern/asset:

```
/patterns/{patternName}/{patternName}.html.php
/patterns/{patternName}/readme.md
/patterns/{patternName}/stylesheet.css
etc...
```

throws a 404. The following route patterns seem to work ok:

```
/patterns/
/patterns/{patternName}/
/patterns/{patternName}/assets
/patterns/{patternName}/preview
```

For the time being I'm just accessing patterns via apache, but it'd sure be great to solve to run in environments without apache.

**Comment by shoesforindustry** [comment]
I had actually moved the `index.css` and `index.min.css` and js equivalents to the assets folder.
I can create patterns and navigate to them I think, it seems to be working OK, but of course hard to tell exactly without JS and CSS.
I've noticed problems with nginx when using codekit and file name of the type `name.min.ext.
It maybe this? But of course of does not seem to recognise the config commands so I cannot check.
I'd like to start working with this for a new project, but so far have got no where.

**Comment by jenstornell** [comment]
@shoesforindustry I strongly recommend you to switch to http://gulpjs.com/ instead. It takes a little more time to learn but after the switch you will probably never go back.

**Comment by shoesforindustry** [comment]
Jens, I'm not adverse to using gulp ;-), but we need to use Codekit on this one. In any event I cannot get the patterns plugin to load it's own JS /CSS when not using Codekit, which I think is the problem.

**Comment by shoesforindustry** [comment]
OK, so I've managed to get it working (at least the CSS and JS bit) on an Apache server, it still loads:
`<link rel="stylesheet" href="http://aap.dev/patterns/assets/index.min.css">`
whatever I put in the `config.php`, so how can I change this to load to `assets/index.css`, even if just a botch for now, to see if it is the extra '.' in the filename with Nginx. (The client is nginx, so we have no choice.)

**Comment by shoesforindustry** [comment]
Further to my previous post, I figured out you can edit the bottom of the `lab.php` to alter the loading file, so I now am trying to load index.css & index.js, so far so good, but loading still fails.
In HTML
`http://aap.dev/patterns/assets/dist/index.css`

If I just enter the below in the URL bar of my browser, the file could not be found.
`http://aap.dev/patterns/assets/dist/index.js`

If I just enter the below in the URL bar of my browser, the file is found.
`http://aap.dev/site/plugins/patterns/assets/dist/index.css`

Some sort of routing error? (This is the same nginx conf we use on quite a few different servers/sites.) Anyone any ideas?

**Comment by shoesforindustry** [comment]
I can now get the CSS and JS to load by directly adding the path to the bottom of the lab file e.g.
Replace 
```php 
//$theme->css = file_exists($assets . DS . 'index.css') ? 'assets/patterns/index.css' : $this->url() . '/assets/dist/index.css';
//with
$theme->css = file_exists($assets . DS . 'index.css') ? 'assets/patterns/index.css' : 'http://aap.dev/site/plugins/patterns/assets/dist/index.min.css';
```
But now the HTML and PHP buttons don't work in the interface, so a bit useless really.

Sadly I'm going to have to call a halt to this testing on nginx of the patterns plugin. It is a great idea which I wanted to use, but sadly at the moment can't seem to get running properly.

**Comment by shoesforindustry** [comment]
I'll log another issue to highlight this not seeming to work with ngnix

**Comment by dkerzig** [comment]
+1

**Comment by fabianmichael** [comment]
I tried to setup the Pattern Lab with PHP’s bult-in server for some hours and finally found a solution to make it work. It seems, that the server does not like dots in URLs for some reason (Why? Honestly: WHY?). This results in a wrong value of `$_SERVER['SCRIPT_NAME']`, but the good news is, that you can override this behavior by using a router file. Include something like the following code into your `router.php`:

```php
<?php

$_SERVER['SCRIPT_NAME'] = '/index.php';

require "index.php";
```
Note, that some additional checks should be done to make it work with static resources, the sample above redirects every request to `index.php`

Seems, like other PHP projects are facing similar issues: https://github.com/slimphp/Slim/issues/359

**Comment by paulrobertlloyd** [comment]
@fabianmichael I’m running into the same issue as @shoesforindustry regarding using the pattern plugin with an nginx server. Your fix sounds promising, but trying to work out where/which the `router.php` is. Any clues? Thanks!

**Comment by fabianmichael** [comment]
@paulrobertlloyd You have to pass it as an additional parameter to the `php` command to tell your PHP server, where the rooter file is. Take a look into the PHP manual, there you should find it.
