### ISSUE TITLE
Plugin API for other file types (.less, .styl etc.)

### ISSUE THREAD

**Issue by shoesforindustry** [getkirby-v2/patterns-plugin#32]
Files with a `.less` extension are not formatted like those with a `.css` or `.scss` extension are 
Surely they should be?

**Comment by iamtimm** [comment]
Im having the same issue but with .styl files.

**Comment by lukasbestle** [comment]
The issue is not that Stylus or LESS files are not supported by the plugin, but there are no syntax highlighting rules for them.

See #39, where I added YAML. The more languages we support, the larger the JS file gets.

**Comment by iamtimm** [comment]
Ahh I see, totally understand. Someway is easily plugging in highlighters be
great.

  
![](https://link.nylas.com/open/37jk5p2xlzbii6bxfn8gexmd0/local-
86c17913-b3c0?r=cmVwbHkrMDAyN2IxNzQ2YzY2Zjk0NjIzNWQzYzYxNTYwYWQ4MzNkZGQxZjA2MjVhMTFmODYyOTJjZjAwMDAwMDAxMTNhYjQyZjY5MmExNjljZTA4MDUyZmM4QHJlcGx5LmdpdGh1Yi5jb20=)

On Jul 23 2016, at 4:36 pm, Lukas Bestle &lt;notifications@github.com&gt;
wrote:  

> The issue is not that Stylus or LESS files are not supported by the plugin,
but there are no syntax highlighting rules for them.

>

> See [#39](https://github.com/getkirby-plugins/patterns-
plugin/pull/39&r=cmVwbHkrMDAyN2IxNzQ2YzY2Zjk0NjIzNWQzYzYxNTYwYWQ4MzNkZGQxZjA2MjVhMTFmODYyOTJjZjAwMDAwMDAxMTNhYjQyZjY5MmExNjljZTA4MDUyZmM4QHJlcGx5LmdpdGh1Yi5jb20=),
where I added YAML. The more languages we support, the larger the JS file
gets.

>

> —  
> You are receiving this because you commented.  
> Reply to this email directly, [view it on GitHub](https://github.com
/getkirby-plugins/patterns-
plugin/issues/32#issuecomment-234721437&r=cmVwbHkrMDAyN2IxNzQ2YzY2Zjk0NjIzNWQzYzYxNTYwYWQ4MzNkZGQxZjA2MjVhMTFmODYyOTJjZjAwMDAwMDAxMTNhYjQyZjY5MmExNjljZTA4MDUyZmM4QHJlcGx5LmdpdGh1Yi5jb20=),
or [mute the thread](https://github.com/notifications/unsubscribe-
auth/ACexdM2SgoAuTcYGg8orG8J8lIBuTO48ks5qYib2gaJpZM4Hc_GH&r=cmVwbHkrMDAyN2IxNzQ2YzY2Zjk0NjIzNWQzYzYxNTYwYWQ4MzNkZGQxZjA2MjVhMTFmODYyOTJjZjAwMDAwMDAxMTNhYjQyZjY5MmExNjljZTA4MDUyZmM4QHJlcGx5LmdpdGh1Yi5jb20=).![](https://github.com/notifications/beacon/ACexdG0ARhHvMvTB0GlfMuLmQl06MW3dks5qYib2gaJpZM4Hc_GH.gif)

**Comment by lukasbestle** [comment]
That's a great idea! I will look into this. Some kind of API to extend the supported languages would be great.

**Comment by luxlogica** [comment]
Definitely would not mind a larger JS file, if we could also get syntax highlighting for `.less` and `.pug` files. ;-)
