### ISSUE TITLE
Support for other template languages

### ISSUE THREAD

**Issue by jvgreenaway** [getkirby-v2/patterns-plugin#42]
Would it possible to add Twig support? 

I see there is a Kirby Twig plugin https://github.com/fvsch/kirby-twig.

**Comment by lukasbestle** [comment]
Twig support in which way? Support for Twig syntax highlighting or support for using Twig templates as pattern template when using the `pattern()` helper?

**Comment by abroess** [comment]
IMHO both is charming.

**Comment by lukasbestle** [comment]
Support for Twig syntax highlighting: See #32. If we do this, then by extending the plugin with an API, not by hardcoding additional file types.

Patterns helper: You can write one yourself, this is not baked into the plugin directly. :)

**Comment by jvgreenaway** [comment]
Being able to use Twig wherever a PHP template would normally be used would be awesome. 

@fvsch made some good notes on this topic here https://github.com/fvsch/kirby-twig/issues/13
