### ISSUE TITLE
Create additional preview html

### ISSUE THREAD

**Issue by jakobploens** [getkirby-v2/patterns-plugin#5]
This is against the intentional thought of Kirby Patterns and against the "living styleguide thinking", but sometimes you just have a css file as a pattern, or many different possibilities of one. Think of a button-pattern with many different classes for color, size and maybe icons, like Bootstrap or SemanticUI are using – creating a new pattern for each button is not the right thing to do, but on the other side just showing the basic pattern without any modification isn't showing the different possibilities. Just the readme can't describe this, or has to use images etc which is even worse. Better might be to just have a "{pattern}.demo.php" which will then be used **as preview** instead of the html.php, where you can add demo patterns – of course using your described patterns. So "buttons.demo.php" could look like this:

``` php
<?php

pattern('button', ['class' => 'blue', 'label' => 'Blue button']);
pattern('button', ['class' => 'yellow small', 'label' => 'Yellow small sized button']);
pattern('button', ['class' => 'green medium', 'label' => 'Green medium sized button']);
```

The other use case – just a css file – might be matching when using grids. Here it would also be good to just quick demo the grid with different possibilities and columns.

If there is no demo.php, the html.php will be used. So everything is optional, and you can benefit from both, the living and the well-documented, demo'ed styleguide.

Edit: this could otherwise also be a feature for the config.php and the `preview()` (or a new one) function, to remove the additional file.

**Comment by bastianallgeier** [comment]
That's a great idea!

**Comment by shoesforindustry** [comment]
+ 1

**Comment by jenstornell** [comment]
I will not say if this is a good idea or not but I can tell you how I work with this.

**Base pattern**

- I create a button that has some default styling, maybe just a gray button.
- It contains basic styles in the scss / css. No extra colors.
- It receves parameters from the child pattern, like classes.

**Child pattern**

- I create a child pattern for every button variation.
- Every child pattern has a scss / css that only contains colors.
- The child pattern calls the base pattern and send parameters to it.

**Summery**

Base patterns recive div class names and other parameters but does not style them. It contains base scss / css.

Child patterns send div class names and other parameters to base pattern and contain only colors etc in the scss / css.

**Comment by jakobploens** [comment]
This works, yes, but I see several downsides for complex styles/sites:

- What if you have more than one option to change, not only color, but also size? You should be able to do things like "medium blue" or "x-large orange". Adding the size as child for every color just is a bunch of unnecessary work.
- In general, it is more work when you want to add new styles/options – you not only have to add a class in your css, but also a new folder and a new file. And of course you have to import the css/scss file in your main file.
- Like I already wrote in the initial post, it just feels "wrong" to me – this is my personal feeling – to call a variation of a pattern with another pattern. After all, it is just a different class, but it is still the same pattern.

From a developer's perspective, I think the pattern system is great just the way it is. But as a client/user/patterns-viewer, I'd like to have more possibilites to see.

**Comment by jenstornell** [comment]
I agree about the first two items. My site is not so complex so I did not think that far.

## I do something like this

**In a page pattern:**

```php
pattern('buttons/contact');
```

**In the `buttons/contact pattern`:**

```php
pattern('buttons', ['color' => 'red', 'fontsize'=> 18] );
```

**In the `buttons`**

```php
<div class="button color-<?php echo echo $color; ?> fontsize-<?php echo $fontsize; ?>">
Button
</div>
```

**Comment by jakobploens** [comment]
Of course, this works for smaller (= less complex) sites. And, after all, it's always a matter of personal taste ;)

**Comment by jenstornell** [comment]
For large projects I think the demo can be a very good feature. Less folders.

+1

**Comment by distantnative** [comment]
+1
