### ISSUE TITLE
Cool. How to link it with blueprints/panel?

### ISSUE THREAD

**Issue by cnoss** [getkirby-v2/patterns-plugin#8]
Hi, really smart! I think it would be very nice, if you can link the patterns with blueprint files. The defaults are a good entry, maybe :) They could act like a content inventory. I do not have a clear idea how to link patterns to blueprint, but think it would boost the development process, especially if you follow a "Content first approach". You can define the structure of the content in the defaults. Editors can create content via panel and the development team can work on html/css/js-Stuff synchronously. If there is real content, the pattern uses this content, otherwise it uses the defaults.

**Comment by jenstornell** [comment]
The "problem" of this idea is probably that the panel is not integrated with Kirby. It's separated. If it's going to work it needs to be some kind of bridge between them.

Then I don't know if I like the idea of mashing everything together. It might end up beeing a soup.

As I see it, the pattern plugin is made for developers, not for content writers in the panel.

**Comment by bastianallgeier** [comment]
I think the idea is actually very interesting, but I'm not sure how this could be solved in reality. Most patterns are just a tiny fraction of the entire set of data that is required for a page. Maybe there could be some kind of way to analyze all the patterns in a template and then create/display that content inventory you were speaking about. But I'm not sure if this could be entirely automated. I'm always open for more ideas though.

**Comment by jenstornell** [comment]
I'm not convinced. It sounds like alot of work and not so reliable solutions to make it work. Please don't stress this.

Maybe instead add hooks to Patterns so other developers can filter / add data? Then it would be possible for developers to build something like this... and more...

**Comment by mrunkel** [comment]
Hi @cnoss I'm currently at looking at doing this as we'd like to give our content editors a way to build pages from a predefined set of elements.

We follow the atoms/molecules/organisms model, so I'm looking at making all the organisms available as building blocks for the pages.

We found [TimOetting/kirby-builder](https://github.com/TimOetting/kirby-builder) and are thinking of using that tied into the patterns.   It's built to use snippets and not patterns.

Right now we are evaluating whether to:

1. Make a one-to-one correspondence of snippets to organism patterns where the snippet just calls the pattern in production, but generates the proper defaults for the preview in the panel.
2. Try to adapt kirby-builder to use snippets directly.

Option 1 is more work in the long run (as we'd need to generate default data generators for both patterns and builder snippets), but I think given the fact that the preview function in the snippets and the panel work very differently (vis a vis no js in the panel preview) it might be the best solution.

If I get a complete solution pulled together, I'll post something.

**Comment by lukaskleinschmidt** [comment]
@mrunkel The [modules plugin](https://github.com/getkirby-plugins/modules-plugin) with the [sortable plugin](https://github.com/lukaskleinschmidt/kirby-sortable) is also a great way to handle modules. The modules plugin also offers a [direct way](
https://github.com/getkirby-plugins/modules-plugin#using-together-with-the-patterns-plugin) to integreate those into your patterns.

**Comment by mrunkel** [comment]
@lukaskleinschmidt That is awesome.  If you're ever in Düsseldorf, I'll buy you a beer or two!  Thank you for the tip.

**Comment by lukaskleinschmidt** [comment]
I'm actaully in Aachen so I might take you up on that. 😉
If you have any questions regarding the sortable field feel free to ask. I know the readme is a bit daunting.
